version: 2

# Common steps for building server Docker images
pypi_step: &pypi_step
  name: Init .pypirc
  command: |
    echo -e "[distutils]" >> ~/.pypirc
    echo -e "index-servers =" >> ~/.pypirc
    echo -e "    pypi" >> ~/.pypirc
    echo -e "    longtailbio" >> ~/.pypirc
    echo -e "" >> ~/.pypirc
    echo -e "[pypi]" >> ~/.pypirc
    echo -e "" >> ~/.pypirc
    echo -e "[longtailbio]" >> ~/.pypirc
    echo -e "repository: https://pypi.longtailbio.com" >> ~/.pypirc
    echo -e "username: $LT_PYPI_USERNAME" >> ~/.pypirc
    echo -e "password: $LT_PYPI_PASSWORD" >> ~/.pypirc
    mkdir ~/.pip
    echo -e "[global]" >> ~/.pip/pip.conf
    echo -e "extra-index-url = https://pypi.longtailbio.com/simple/" >> ~/.pip/pip.conf


jobs:
  test_package:
    docker:
      - image: themattrix/tox

    steps:
      - run:
          name: Install Git
          command: apt-get update; apt-get install -y git

      - checkout

      - run:
        <<: *pypi_step

      - run:
          name: Run tests with py35
          command: tox -e py35

      - run:
          name: Run tests with py36
          command: tox -e py36

      - run:
          name: Run tests with pypy3
          command: tox -e pypy3

      - run:
          name: Run pylint
          command: tox -e pylint
          when: always

  deploy:
    docker:
      - image: circleci/python:3.6.3-jessie

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Install Python Dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
        <<: *pypi_step

      - run:
          name: Build package
          command: |
            . venv/bin/activate
            python setup.py bdist_wheel --universal

      - run:
          name: Upload to Longtail PyPi
          command: |
            . venv/bin/activate
            pip install twine
            twine upload -r longtailbio dist/*



workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test_package:
          context: longtail-pypi
      - deploy:
          context: longtail-pypi
          filters:
            branches:
              only: master
          requires:
            - test_package
