version: 2

jobs:
  build:
    docker:
      - image: themattrix/tox

    steps:
      - run:
          name: Install Git
          command: apt-get update; apt-get install -y git

      - checkout

      - run:
          name: Init .pypirc
          command: |
            echo -e "[distutils]" >> ~/.pypirc
            echo -e "index-servers =" >> ~/.pypirc
            echo -e "    pypi" >> ~/.pypirc
            echo -e "    longtailbio" >> ~/.pypirc
            echo -e "" >> ~/.pypirc
            echo -e "[pypi]" >> ~/.pypirc
            echo -e "" >> ~/.pypirc
            echo -e "[longtailbio]" >> ~/.pypirc
            echo -e "repository: https://pypi.longtailbio.com" >> ~/.pypirc
            echo -e "username: $LT_PYPI_USERNAME" >> ~/.pypirc
            echo -e "password: $LT_PYPI_PASSWORD" >> ~/.pypirc

      - run:
          name: Init ~/.pip/pip.conf
          command: |
            mkdir ~/.pip
            echo -e "[global]" >> ~/.pip/pip.conf
            echo -e "extra-index-url = https://pypi.longtailbio.com/simple/" >> ~/.pip/pip.conf

      - run:
          name: Run tests with py35
          command: tox -e py35

      - run:
          name: Run tests with py36
          command: tox -e py36

      - run:
          name: Run tests with pypy3
          command: tox -e pypy3

      - run:
          name: Run pylint
          command: tox -e pylint
          when: always
